services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
    - 8080:8080
    environment:
      BACKEND_PORT: 9000
      BACKEND_DNS: localhost
  backend:
    container_name: backend
    build: ./backend
    environment:
      REDIS_DNS: redis
      

