name: CICD pipeline
on: [push, workflow_dispatch]
env:
  docker_username: andreas528
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build code
        run: |
            cd frontend
            go build
      - name: upload code
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
  Testing:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v5
        with:
          name: code
          path: .
      - name: Testing
        run: |
            cd frontend
            go test

  Docker-image:
    runs-on: ubuntu-latest
    needs: [Testing]
    permissions:
      packages: write
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Build Docker
        run: bash ci/build-docker.sh
      - name: Push Docker
        run: bash ci/push-docker.sh

  Deploy:
    runs-on: ubuntu-latest
    needs: [Docker-image]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Deploy on Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          kubectl --kubeconfig kubeconfig apply -f ./kubernetes
        
        
