name: CICD pipeline
on: [push, workflow_dispatch]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build code
        run: |
            cd frontend
            go build
      - name: upload code
        uses: actions/upload-artifact@v4
        with: 
          name: Code
          path: .
          include-hidden-files: true
  Testing:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v5
        with:
          name: Code
          path: .
      - name: Testing
        run: |
            cd frontend
            go test
        
